# -*- coding: utf-8 -*-
"""Pingpong.Players-POS-ITT103-SP2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uTjyuH3lBYzalZsQLlrz0LSHvVoZi0U
"""

# Product catalog with product names, prices, and stock quantities
product_catalog = {
    "Rice": {"price": 55, "stock": 50},
    "Bread": {"price": 45, "stock": 30},
    "Milk": {"price": 60, "stock": 25},
    "Eggs": {"price": 8, "stock": 100},
    "Sugar": {"price": 50, "stock": 40},
    "Cooking Oil": {"price": 75, "stock": 35},
    "Soft Drink": {"price": 25, "stock": 60},
    "Bottled Water": {"price": 15, "stock": 80},
    "Detergent": {"price": 120, "stock": 20},
    "Dish Soap": {"price": 35, "stock": 45}
}

# Shopping cart to store items the customer wants to buy
shopping_cart = []

# Display welcome message
print("="*70)
print("BEST BUY RETAIL STORE")
print("Your One-Stop Shop for Groceries, Beverages, and Household Items")
print("="*70)

# Main program loop - keeps running until user chooses to exit
while True:

    # Display main menu options
    print("\nMAIN MENU")
    print("="*40)
    print("1. View Products")
    print("2. Add to Cart")
    print("3. Remove from Cart")
    print("4. View Cart")
    print("5. Checkout")
    print("6. New Transaction")
    print("7. Exit")
    print("="*40)

    # Get user's menu choice
    choice = input("Enter your choice (1-7): ").strip()

    # OPTION 1: VIEW PRODUCTS
    if choice == "1":
        # Display product catalog header
        print("\n" + "="*70)
        print("PRODUCT CATALOG")
        print("="*70)
        print(f"{'Product':<20} {'Category':<15} {'Price':<10} {'Stock':<10}")
        print("-"*70)

        # Loop through each product in the catalog with categories
        for product_name, details in product_catalog.items():
            # Assign categories based on product type
            if product_name in ["Rice", "Bread", "Milk", "Eggs", "Sugar", "Cooking Oil"]:
                category = "Groceries"
            elif product_name in ["Soft Drink", "Bottled Water"]:
                category = "Beverages"
            else:
                category = "Household"

            # Check if stock is low (less than 5)
            if details['stock'] < 5:
                stock_status = str(details['stock']) + " units - LOW STOCK"
            else:
                stock_status = str(details['stock']) + " units"

            # Display product information
            print(f"{product_name:<20} {category:<15} ${details['price']:<9} {stock_status:<10}")

        print("="*70)

        # Check for low stock items and display alert
        print("\nCHECKING LOW STOCK ITEMS:")
        low_stock_count = 0

        for product, details in product_catalog.items():
            if details["stock"] < 5:
                print("  - " + product + ": " + str(details['stock']) + " units remaining")
                low_stock_count = low_stock_count + 1

        if low_stock_count == 0:
            print("  All items have sufficient stock.")

        print()

    # OPTION 2: ADD TO CART
    elif choice == "2":
        print("\n--- ADD ITEM TO CART ---")

        # Show available products
        print("\nAvailable Products:")
        print("GROCERIES:")
        for product_name in product_catalog.keys():
            if product_name in ["Rice", "Bread", "Milk", "Eggs", "Sugar", "Cooking Oil"]:
                print("  - " + product_name)

        print("BEVERAGES:")
        for product_name in product_catalog.keys():
            if product_name in ["Soft Drink", "Bottled Water"]:
                print("  - " + product_name)

        print("HOUSEHOLD ITEMS:")
        for product_name in product_catalog.keys():
            if product_name in ["Detergent", "Dish Soap"]:
                print("  - " + product_name)

        # Get product name from user
        product_name = input("\nEnter product name: ")
        product_name = product_name.title()  # Capitalize first letter of each word

        # Check if product exists in catalog
        if product_name not in product_catalog:
            print("Error: Product not found!")
            continue  # Go back to main menu

        # Check if product is in stock
        if product_catalog[product_name]["stock"] <= 0:
            print("Error: Product is out of stock!")
            continue  # Go back to main menu

        # Get quantity from user
        try:
            quantity = int(input("Enter quantity: "))

            # Validate quantity is positive
            if quantity <= 0:
                print("Error: Quantity must be greater than zero!")
                continue  # Go back to main menu

        except ValueError:
            print("Error: Please enter a valid number!")
            continue  # Go back to main menu

        # Check if enough stock is available
        if quantity > product_catalog[product_name]["stock"]:
            print("Error: Only " + str(product_catalog[product_name]['stock']) + " units available!")
            continue  # Go back to main menu

        # Check if item is already in cart
        item_exists = False

        for item in shopping_cart:
            if item["name"] == product_name:
                # Update quantity if item already in cart
                item["quantity"] = item["quantity"] + quantity
                print("Added " + str(quantity) + " more " + product_name + "(s) to cart!")
                item_exists = True
                break

        # If item not in cart, add new item
        if item_exists == False:
            new_item = {
                "name": product_name,
                "quantity": quantity,
                "price": product_catalog[product_name]["price"]
            }
            shopping_cart.append(new_item)
            print("Added " + str(quantity) + " " + product_name + "(s) to cart!")

    # OPTION 3: REMOVE FROM CART
    elif choice == "3":
        # Check if cart is empty
        if len(shopping_cart) == 0:
            print("\nError: Cart is empty!")
            continue  # Go back to main menu

        print("\n--- REMOVE ITEM FROM CART ---")

        # Display current cart items
        print("\nCurrent Cart:")
        for item in shopping_cart:
            print("  - " + item['name'] + ": " + str(item['quantity']) + " units")

        # Get product name to remove
        product_name = input("\nEnter product name to remove: ")
        product_name = product_name.title()

        # Search for product in cart
        item_found = False

        for item in shopping_cart:
            if item["name"] == product_name:
                item_found = True

                # Get quantity to remove
                try:
                    quantity = int(input("Enter quantity to remove (current: " + str(item['quantity']) + "): "))

                    # Validate quantity
                    if quantity <= 0:
                        print("Error: Quantity must be greater than zero!")
                        break

                    # Remove item completely or reduce quantity
                    if quantity >= item["quantity"]:
                        shopping_cart.remove(item)
                        print("Removed all " + product_name + "(s) from cart!")
                    else:
                        item["quantity"] = item["quantity"] - quantity
                        print("Removed " + str(quantity) + " " + product_name + "(s) from cart!")

                    break

                except ValueError:
                    print("Error: Please enter a valid number!")
                    break

        if item_found == False:
            print("Error: " + product_name + " not found in cart!")

    # OPTION 4: VIEW CART
    elif choice == "4":
        # Check if cart is empty
        if len(shopping_cart) == 0:
            print("\nCart is empty!")
            continue  # Go back to main menu

        # Display cart header
        print("\n" + "="*70)
        print("SHOPPING CART")
        print("="*70)
        print(f"{'Item':<20} {'Quantity':<10} {'Unit Price':<12} {'Total':<12}")
        print("-"*70)

        # Calculate subtotal while displaying items
        subtotal = 0

        for item in shopping_cart:
            item_total = item["quantity"] * item["price"]
            subtotal = subtotal + item_total
            print(f"{item['name']:<20} {item['quantity']:<10} ${item['price']:<11} ${item_total:<11}")

        # Display subtotal
        print("-"*70)
        print(f"{'Subtotal:':<52} ${subtotal:.2f}")
        print("="*70)

    # OPTION 5: CHECKOUT
    elif choice == "5":
        # Check if cart is empty
        if len(shopping_cart) == 0:
            print("\nError: Cannot checkout because cart is empty!")
            continue  # Go back to main menu

        print("\n" + "="*70)
        print("CHECKOUT")
        print("="*70)

        # Calculate subtotal
        subtotal = 0

        for item in shopping_cart:
            subtotal = subtotal + (item["quantity"] * item["price"])

        # Apply discount for orders over 5000
        discount = 0

        if subtotal > 5000:
            discount = subtotal * 0.05
            print("5% Discount Applied: -$" + str(discount))

        # Calculate after discount, tax, and total
        subtotal_after_discount = subtotal - discount
        tax = subtotal_after_discount * 0.10
        total_due = subtotal_after_discount + tax

        # Display totals
        print("\nSubtotal: $" + str(subtotal))

        if discount > 0:
            print("Discount (5%): -$" + str(discount))
            print("Subtotal after discount: " + str(subtotal_after_discount))

        print("Sales Tax (10%): $" + str(tax))
        print("TOTAL DUE: $" + str(total_due))
        print("-"*70)

        # Process payment
        payment_valid = False

        while payment_valid == False:
            try:
                amount_paid = float(input("Enter amount received: $"))

                if amount_paid < total_due:
                    print("Error: Insufficient amount! Need $" + str(total_due - amount_paid) + " more.")
                else:
                    payment_valid = True

            except ValueError:
                print("Error: Please enter a valid number!")

        # Calculate change
        change = amount_paid - total_due

        # GENERATE RECEIPT
        print("\n" + "="*70)
        print("BEST BUY RETAIL STORE")
        print("123 Main Street, Cityville")
        print("Tel: (123) 456-7890")
        print("Your One-Stop Shop for Groceries, Beverages, and Household Items")
        print("="*70)
        print("RECEIPT")
        print("-"*70)
        print(f"{'Item':<20} {'Qty':<5} {'Unit Price':<12} {'Total':<12}")
        print("-"*70)

        # Display each item in receipt
        for item in shopping_cart:
            item_total = item["quantity"] * item["price"]
            print(f"{item['name']:<20} {item['quantity']:<5} ${item['price']:<11} ${item_total:<11}")

        # Display totals in receipt
        print("-"*70)
        print(f"{'Subtotal:':<48} ${subtotal:.2f}")

        if discount > 0:
            print(f"{'Discount (5%):':<48} -${discount:.2f}")
            print(f"{'Subtotal after discount:':<48} ${subtotal_after_discount:.2f}")

        print(f"{'Sales Tax (10%):':<48} ${tax:.2f}")
        print(f"{'TOTAL DUE:':<48} ${total_due:.2f}")
        print(f"{'Amount Paid:':<48} ${amount_paid:.2f}")
        print(f"{'Change:':<48} ${change:.2f}")
        print("="*70)
        print("Thank you for shopping at Best Buy Retail Store!")
        print("We appreciate your business!")
        print("="*70 + "\n")

        # Update stock quantities after purchase
        for item in shopping_cart:
            product_catalog[item["name"]]["stock"] = product_catalog[item["name"]]["stock"] - item["quantity"]

        # Clear the shopping cart
        shopping_cart = []

        # Check and display low stock alert
        print("LOW STOCK CHECK:")
        low_stock_items = []

        for product, details in product_catalog.items():
            if details["stock"] < 5:
                low_stock_items.append(product + ": " + str(details['stock']) + " units")

        if len(low_stock_items) > 0:
            print("The following items have less than 5 units remaining:")
            for item in low_stock_items:
                print("  - " + item)
        else:
            print("All items have sufficient stock.")

        print()

        # Ask if user wants to continue
        continue_transaction = input("Start new transaction? (y/n): ")
        continue_transaction = continue_transaction.lower()

        if continue_transaction != 'y':
            print("\nThank you for using Best Buy Retail Store POS System!")
            break  # Exit the program

    # OPTION 6: NEW TRANSACTION
    elif choice == "6":
        # Check if cart has items before clearing
        if len(shopping_cart) > 0:
            confirm = input("Clear current cart? (y/n): ")
            confirm = confirm.lower()

            if confirm == 'y':
                shopping_cart = []
                print("Cart cleared! Ready for new transaction.")
        else:
            print("Ready for new transaction.")

    # OPTION 7: EXIT
    elif choice == "7":
        print("\nThank you for using Best Buy Retail Store POS System!")
        break  # Exit the while loop and end program

    # Invalid choice handling
    else:
        print("Error: Invalid choice! Please enter a number between 1 and 7.")